= Ruby
:toc:

== coding マジックコメント

2.0.0 以降ではデフォルトが UTF-8 になったため、
UTF-8 の場合はマジックコメント不要。

https://www.ruby-lang.org/ja/news/2013/02/24/ruby-2-0-0-p0-is-released/

衝撃の事実!? "# -*- encoding: utf-8 -*-"じゃなくてもいいんです！ - Qiita +
https://qiita.com/jnchito/items/8f44a3c52d4669fefa93

Emacs の ruby-mode でマジックコメントを自動挿入しない設定 - Qiita +
https://qiita.com/tetsuo_jp/items/c05095931ae080f89d21

[source,lisp]
--------------------------------
(setq ruby-insert-encoding-magic-comment nil)
--------------------------------


== Bundler

[source]
--------------------------------
bundle config set --local path 'vendor/bundle'
--------------------------------

---

> The main change in bundler 2.1 is that 
> deprecations for upcoming breaking changes in bundler 3 will be turned on by default.

https://bundler.io/v2.1/whats_new.html

---

gem install・bundle installなしでgemを使ったスクリプトを実行する方法 - Qiita +
https://qiita.com/takahashim/items/c7b5d0e30b4aeb73d8f8




== Minitest

[source,ruby]
--------------------------------
require "minitest/autorun"

class TestFoo < Minitest::Test
  def test_foo
    assert_equal(3, 1 + 2, "...")
  end
end
--------------------------------

---

minitest/assertions.rb at v5.14.4 · seattlerb/minitest +
https://github.com/seattlerb/minitest/blob/v5.14.4/lib/minitest/assertions.rb

[source,ruby]
--------------------------------
assert_equal(exp, act, msg)
flunk(msg = nil)
pass()
--------------------------------




== Standard

Style :: RuboCop Docs +
https://docs.rubocop.org/rubocop/cops_style.html

[source]
--------------------------------
Style/HashSyntax
  { :a => 1 } を禁止
Style/MethodCallWithoutArgsParentheses
  不要な括弧を禁止
--------------------------------




== 各バージョンのメンテナンス状況 / EOL

Ruby Maintenance Branches +
https://www.ruby-lang.org/en/downloads/branches/


== 標準ライブラリ


=== ERB

result_with_hash: 2.5 以降

サンプルコードでわかる！Ruby 2.5の主な新機能と変更点 Part 1 - Qiita +
https://qiita.com/jnchito/items/f182b6f0093a6a3701a1


=== REXML

3.0 で default gem から bundled gemに変更

週刊Railsウォッチ（20201005前編）Ruby 2.7.2がリリース、Shopifyのモジュラー化gem「packwerk」、stimulus_reflexほか｜TechRacho（テックラッチョ）〜エンジニアの「？」を「！」に〜｜BPS株式会社 +
https://techracho.bpsinc.jp/hachi8833/2020_10_05/98286




== default gem / bundled gem

(2024-01-29) 徹底解説！ default gemsとbundled gemsのすべて | gihyo.jp +
https://gihyo.jp/article/2024/01/ruby3.3-bundled-gems

ruby/doc/standard_library.md at master · ruby/ruby +
https://github.com/ruby/ruby/blob/master/doc/standard_library.md

Standard Gems +
https://stdgems.org/


== その他

=== <<~（squiggly heredoc）（2.3 以降）

サンプルコードでわかる！Ruby 2.3の主な新機能 #Ruby - Qiita +
https://qiita.com/jnchito/items/0faac073cb77417d61c7


=== require なしで pp が使える（2.5 以降）

サンプルコードでわかる！Ruby 2.5の主な新機能と変更点 Part 2 - Qiita +
https://qiita.com/jnchito/items/0d2d17a79a3e82fe3815


=== 終端なし Range（2.6 以降）

Ruby 2.6.0 Released +
https://www.ruby-lang.org/ja/news/2018/12/25/ruby-2-6-0-released/

NEWS for Ruby 2.6.0 (Ruby 3.2 リファレンスマニュアル) +
https://docs.ruby-lang.org/ja/latest/doc/news=2f2_6_0.html
